package io.hyperswitch

import com.facebook.react.PackageList
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import io.hyperswitch.react.HyperPackage
import io.hyperswitch.react.HyperReactPackageProvider

/**
 * Host-side implementation of [HyperReactPackageProvider].
 *
 * This class lives in :app so it can reference the autolinked [PackageList]
 * generated by the React Native Gradle plugin.
 */
class HyperswitchReactPackageProvider : HyperReactPackageProvider() {
    override fun getPackages(host: ReactNativeHost): List<ReactPackage> {
        return PackageList(host).packages.apply {
            add(HyperPackage())
        }
    }
}
