-keep class com.reactnativehyperswitchscancard.**  { *; }
-keep class com.reactnativehyperswitchnetcetera3ds.** { *; }
-keep class io.sentry.react.** { *; }
-dontwarn com.horcrux.svg.**
-dontwarn org.slf4j.impl.**