plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group = "io.hyperswitch"
version = paymentMethodsVersion

android {
    namespace 'io.hyperswitch.paymentmethods'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    api project(':app')
    implementation libs.kotlin.coroutinesAndroid
}
